# Generated by Django 5.2.12 on 2026-03-09 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.CharField(blank=True, max_length=120)),
                ('init_point', models.URLField(blank=True, max_length=800)),
                ('sandbox_init_point', models.URLField(blank=True, max_length=800)),
                ('mp_payment_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('INIT', 'Init'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'Unknown')], default='INIT', max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mp_payment', to='orders.order')),
            ],
        ),
    ]
