services:
  db:
    image: postgres:16
    container_name: 3darg_db
    env_file:
    - ./3darg-backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: ./3darg-backend
    container_name: 3darg_web
    env_file:
      - ./3darg-backend/.env
    volumes:
      - ./3darg-backend:/app
      - ./3darg-backend/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ./start-server.sh
    restart: unless-stopped

  frontend:
    build: ./ecommerce-frontend
    container_name: ecommerce-frontend
    env_file:
      - ./ecommerce-frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./ecommerce-frontend:/app
      - /app/node_modules
    depends_on:
      - web
    restart: unless-stopped


volumes:
  postgres_data: