# Generated by Django 5.2.12 on 2026-03-03 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('brand_type', models.CharField(choices=[('services', 'Services'), ('ecommerce', 'Ecommerce'), ('hybrid', 'Hybrid')], default='services', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_navbar', models.BooleanField(default=True)),
                ('navbar_order', models.PositiveIntegerField(default=0)),
                ('slogan', models.CharField(blank=True, max_length=160)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='brands/covers/')),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Marca madre (ej: 3DARG). Dejar vacío si esta marca es la principal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='brands.brand')),
            ],
            options={
                'ordering': ['navbar_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrandLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='brands.brand')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
    ]
