# Generated by Django 5.2.14 on 2026-05-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='page_config',
            field=models.JSONField(blank=True, default=dict, help_text='Personalización de la landing. Claves disponibles: sections (lista de secciones a mostrar), hero_style (minimal|full|split), lifestyle_headline, lifestyle_subheadline, lifestyle_cta, features ([{icon, title, desc}]), stats ([{value, label}]), newsletter_title, newsletter_subtitle, newsletter_cta.'),
        ),
    ]
