# Generated by Django 5.2.17 on 2026-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_add_page_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración de Meta Business por marca. Claves disponibles: pixel_id, conversions_api_access_token, catalog_id, whatsapp_business_phone_id.'),
        ),
    ]
