# Generated by Django 5.2.17 on 2026-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_meta_catalog_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sku_prefix',
            field=models.CharField(blank=True, help_text='Código corto para el SKU de productos de esta marca (ej: LUMY, PYG, MSL, CYW). Elegilo con cuidado: una vez que hay productos usándolo no se debe cambiar (rompería el significado de los SKU ya publicados en la web/Mercado Libre). Vacío = se usa el slug en mayúsculas como fallback.', max_length=10),
        ),
    ]
