# Generated by Django 5.2.17 on 2026-10-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_user_id', models.BigIntegerField(blank=True, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credenciales de Mercado Libre',
                'verbose_name_plural': 'Credenciales de Mercado Libre',
            },
        ),
    ]
