# Generated by Django 5.2.17 on 2026-10-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLListingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_template', models.TextField(default='Dale a tus galletitas, tortas y piezas de cerámica un acabado profesional con este set de cortante + marcador. Diseñado para lograr cortes limpios y detalles bien definidos en cada pieza, de forma simple y rápida.\n\n-----------------------------------\n¿QUÉ INCLUYE?\n-----------------------------------\n- 1 (un) cortante: corta el contorno de la pieza.\n- 1 (un) marcador / sello: imprime el diseño y los detalles sobre la masa.\n\nPrimero marcás, después cortás: así obtenés piezas prolijas, con relieve y todas iguales.\n\n-----------------------------------\nFICHA TÉCNICA\n-----------------------------------\n- Material: PLA (ácido poliláctico), plástico biodegradable de origen vegetal.\n- Apto para contacto con alimentos.\n- Medidas: $medidas.\n- Composición: 2 piezas (marcador + cortante).\n- Diseño: $modelo\n- Fabricación: Impresión 3D.\n\n-----------------------------------\nUSOS RECOMENDADOS\n-----------------------------------\n- Masa para galletitas (de manteca, de jengibre, decoradas, etc.).\n- Pasta de azúcar / fondant para decorar tortas, cupcakes y cookies.\n- Arcilla, porcelana fría y cerámica.\n- Masas de modelar y actividades con chicos.\n\nIdeal para pastelería profesional, emprendimientos de cookies decoradas, mesas dulces, eventos, ceramistas y para usar en casa.\n\n-----------------------------------\nCUIDADO Y LIMPIEZA\n-----------------------------------\n- Lavar únicamente con AGUA FRÍA y detergente suave.\n- NO usar agua caliente, lavavajillas ni microondas.\n- NO llevar al horno ni exponer a fuentes de calor (el PLA puede deformarse).\n- Secar bien antes de guardar.\n- Tip: enharinar levemente el cortante y el marcador antes de usar para que la masa no se pegue.\n\n-----------------------------------\n¿POR QUÉ COMPRARNOS?\n-----------------------------------\n- TRABAJAMOS CON STOCK PERMANENTE: despachamos tu compra rápido, sin demoras de fabricación.\n- Cada pieza es revisada antes del envío para garantizar bordes limpios y buena terminación.\n- Materiales seguros y amigables con el medio ambiente.\n- Atención personalizada: respondemos todas tus consultas a la brevedad.\n- Ventas mayoristas y por cantidad para emprendedores y comercios: consultanos.\n\n-----------------------------------\nPREGUNTAS FRECUENTES\n-----------------------------------\n¿Es apto para alimentos?\nSí, está fabricado en PLA, material apto para contacto con alimentos.\n\n¿Se puede lavar en lavavajillas?\nNo. Recomendamos lavar a mano con agua fría para conservar su forma.\n\n¿Sirve para fondant y cerámica?\nSí, funciona tanto en masas comestibles como en arcilla, porcelana fría y cerámica. Recomendamos usar piezas distintas para alimentos y para cerámica.\n\n¿Tienen stock?\nSí, trabajamos con stock disponible para que recibas tu pedido lo antes posible.\n\n¿Hacen descuentos por cantidad?\nSí, consultanos por compras mayoristas.\n\n-----------------------------------\nSi tenés alguna duda, escribinos por la sección de preguntas. ¡Estamos para ayudarte!')),
            ],
            options={
                'verbose_name': 'Plantilla de descripción ML',
                'verbose_name_plural': 'Plantilla de descripción ML',
            },
        ),
    ]
