# Generated by Django 5.2.17 on 2026-09-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('segmento', models.CharField(choices=[('cotillon', 'Cotillón / regalería (venta bajo pedido)'), ('empresa', 'Empresa (máquina in-situ, impresión remota)'), ('submarca', 'Sub-marca del grupo (shopping, gimnasio, etc.)'), ('alquiler', 'Alquiler para marca privada (edición limitada)'), ('otro', 'Otro')], max_length=20)),
                ('mensaje', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
