# Generated by Django 5.2.14 on 2026-06-03 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='member_discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Descuento (%) que reciben los usuarios con cuenta sobre este producto. 0 = sin descuento.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='members_only',
            field=models.BooleanField(default=False, help_text='Si está activo, el producto solo es visible y comprable por usuarios con cuenta.'),
        ),
    ]
