# Generated by Django 5.2.17 on 2026-08-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_member_discount_percent_product_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bambuddy_file_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID del archivo en BamBuddy Library. Si está seteado, se envía a imprimir automáticamente al pagarse una orden.', null=True),
        ),
    ]
