# Generated by Django 5.2.17 on 2026-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_bambuddy_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='google_product_category',
            field=models.CharField(blank=True, help_text="Categoría de la taxonomía de Google/Meta (ej: '1239' o 'Sporting Goods > Exercise & Fitness'). Usada en el feed de Meta Catalog.", max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='Identificador único de catálogo (feeds de Meta/Google). Se autogenera desde el ID si se deja vacío.', max_length=64),
        ),
    ]
