# Generated by Django 5.2.17 on 2026-09-15 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_backfill_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categoria padre, para armar jerarquias (ej: Cortantes > Halloween). Vacio = categoria de nivel superior.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category'),
        ),
    ]
