# Generated by Django 5.2.17 on 2026-09-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bundle_discounts',
            field=models.JSONField(blank=True, default=list, help_text='Descuento por volumen (mismo producto). Lista de tramos, ej: [{"quantity": 2, "discount_percent": 10}, {"quantity": 3, "discount_percent": 15}]. Vacío = sin oferta por cantidad (no se muestra el selector en el frontend). El % se aplica sobre el precio ya resuelto (de lista o de socio) — no se acumula con member_discount_percent, se toma el mejor de los dos automáticamente vía unit_price_for().'),
        ),
    ]
