# Generated by Django 5.2.17 on 2026-10-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_bundle_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bundle_discounts',
            field=models.JSONField(blank=True, default=list, help_text='Descuento por volumen (mismo producto). Lista de tramos, ej: [{"quantity": 2, "discount_percent": 10}, {"quantity": 3, "discount_percent": 15}]. Vacío = sin oferta por cantidad (no se muestra el selector en el frontend). El % se aplica sobre el precio ya resuelto (de lista o de socio) — se COMBINA con member_discount_percent (no se elige el mejor de los dos), vía unit_price_for().'),
        ),
    ]
