# Generated by Django 5.2.17 on 2026-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_bundle_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_category_id',
            field=models.CharField(blank=True, help_text='Categoría de Mercado Libre (ej: MLA1234), distinta de la Category interna. Requerida para publicar.', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_item_id',
            field=models.CharField(blank=True, help_text='ID del ítem en Mercado Libre (ej: MLA123456789). Se completa solo al publicar.', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso en kg. Requerido por Mercado Libre para calcular el costo de envío (Mercado Envíos).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
