# Generated by Django 5.2.17 on 2026-10-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_campos_mercadolibre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ml_category_id',
            field=models.CharField(blank=True, default='MLA375405', help_text="Categoría de Mercado Libre, distinta de la Category interna. Default MLA375405 = 'Cortantes' (sirve para todo el catálogo de Lumy); cambiar si el producto es de otro rubro.", max_length=32),
        ),
    ]
