# Generated by Django 5.2.17 on 2026-10-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_ml_category_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='channel',
            field=models.CharField(choices=[('both', 'Ambos (web y Mercado Libre)'), ('web', 'Solo página web'), ('ml', 'Solo Mercado Libre')], default='both', help_text="A dónde se muestra esta foto. 'Ambos' es el comportamiento de siempre.", max_length=10),
        ),
    ]
