# Generated by Django 5.2.17 on 2026-10-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_imagen_por_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='ml_order',
            field=models.PositiveIntegerField(blank=True, help_text='Orden en la publicación de Mercado Libre, si querés que sea distinto al de la web. Vacío = usa el mismo orden que la web.', null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de la foto en la página web.'),
        ),
    ]
