# Generated by Django 5.2.17 on 2026-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_orden_ml_independiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sku_prefix',
            field=models.CharField(blank=True, help_text='Código corto para el SKU de productos de esta categoría (ej: COR para Cortantes, LLA para Llaveros). Solo hace falta cargarlo en categorías de nivel superior (sin categoría padre) — las subcategorías heredan el código de su raíz para no atar el SKU a una subcategoría que puede reordenarse. Igual que Brand.sku_prefix: evitar cambiarlo una vez que hay productos usándolo. Vacío = se usan las primeras letras del slug como fallback.', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Color del producto, solo informativo/descriptivo (no es una variante con stock propio — para eso falta un modelo de variantes que hoy no existe). Se usa para armar el SKU si está cargado.', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Tamaño del producto, solo informativo/descriptivo (mismo criterio que color). Se usa para armar el SKU si está cargado.', max_length=50, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Identificador único de catálogo, compartido entre la web, el feed de Google/Meta, Mercado Libre y presupuestos3d. Se autogenera con el formato MARCA-CATEGORIA-NNNNNN[-VARIANTE] (ej: LUMY-COR-000037 o MSL-ARO-000401-VERDE) a partir de la marca, la categoría raíz del producto y color/tamaño si están cargados — ver Product.generate_sku(). Una vez generado queda fijo: no se recalcula solo si después cambiás la categoría o el color, porque ya pudo haberse publicado en Mercado Libre o en el feed.', max_length=64, unique=True),
        ),
    ]
