# Generated by Django 5.2.17 on 2026-10-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_regenerar_skus_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available_ml',
            field=models.BooleanField(default=True, help_text="Habilita/deshabilita este producto puntualmente en Mercado Libre, sin tocar la web. Desactivarlo pausa la publicación la próxima vez que corras la acción 'Publicar/Actualizar en Mercado Libre'; reactivarlo la vuelve a poner activa. También se apaga solo cuando Mercado Libre avisa (webhook) que el ítem ya no está activo (pausado, cerrado, eliminado) — ver mercadolibre/services.py::handle_item_notification()."),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available_web',
            field=models.BooleanField(default=True, help_text="Habilita/deshabilita este producto puntualmente en la web (y el feed de Google/Meta), sin tocar su publicación en Mercado Libre. Además de esto tiene que estar activo 'is_available' (el apagado general)."),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Identificador único de catálogo, compartido entre la web, el feed de Google/Meta, Mercado Libre y presupuestos3d. Se autogenera con el formato MARCA-CATEGORIA[-ID_SUBCATEGORIA]-NNNNNN[-VARIANTE] (ej: LUMY-COR-000037, LUMY-COR-04-000001 si la subcategoría tiene código propio cargado, o MSL-ARO-000401-VERDE) a partir de la marca, la categoría raíz del producto, el código propio de la subcategoría si está cargado y color/tamaño si están cargados — ver Product.generate_sku(). Con subcategoría, NNNNNN es un contador local a esa subcategoría (1, 2, 3...); sin subcategoría, es el pk global del producto. Una vez generado queda fijo: no se recalcula solo si después cambiás la categoría o el color, porque ya pudo haberse publicado en Mercado Libre o en el feed.', max_length=64, unique=True),
        ),
    ]
