# Generated by Django 5.2.17 on 2026-10-08 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_subcategorias_todos_y_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ml_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión que cobra Mercado Libre sobre el precio de venta (varía ~11,8%–17,14% según categoría/tipo de publicación).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión Mercado Libre (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo fijo por unidad vendida que cobra Mercado Libre (depende del precio, escalonado — cargalo a mano según la tabla vigente de ML).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cargo fijo Mercado Libre'),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_gross_income_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingresos Brutos (IIBB) aplicable según la provincia del dueño.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ingresos Brutos Mercado Libre (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_other_variable_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cualquier otro costo variable sobre el precio (ej: cuotas sin interés). Vacío/0 = no aplica.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Otro costo variable Mercado Libre (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de envío que absorbe el vendedor en esta venta, si corresponde (Mercado Envíos full/flex, etc.).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de envío Mercado Libre'),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA aplicable a esta venta, si corresponde.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='IVA Mercado Libre (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='web_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión sobre el precio de venta en este canal (ej: la de MercadoPago u otro medio de pago), si corresponde.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión Página web (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='web_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo fijo por unidad vendida en este canal, si corresponde.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cargo fijo Página web'),
        ),
        migrations.AddField(
            model_name='product',
            name='web_gross_income_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingresos Brutos (IIBB) aplicable según la provincia del dueño.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ingresos Brutos Página web (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='web_other_variable_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cualquier otro costo variable sobre el precio (ej: cuotas sin interés). Vacío/0 = no aplica.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Otro costo variable Página web (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='web_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de envío que absorbe el vendedor en esta venta, si corresponde.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de envío Página web'),
        ),
        migrations.AddField(
            model_name='product',
            name='web_vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA aplicable a esta venta, si corresponde.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='IVA Página web (%)'),
        ),
    ]
