# Generated by Django 5.2.17 on 2026-10-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_canal_pricing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cutter_size',
            field=models.CharField(blank=True, choices=[('mini', 'Mini'), ('chico', 'Chico'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('oreo_24', 'Oreo 24cm')], default='mediano', help_text='Tamaño de costeo del cortante (la pieza, no el diseño) — se usa SOLO para traer el costo de fabricación desde presupuestos3d en la pantalla de Precio/Stock/Canales (ver cost_sku()), no afecta el SKU propio del producto. Vacío = no se busca costo por tamaño (producto no es un cortante). Si el tamaño elegido todavía no tiene SKU sintético cargado en COST_SKU_BY_CUTTER_SIZE, el costo queda en "no disponible" sin romper nada.', max_length=20, verbose_name='Tamaño de cortante'),
        ),
    ]
