# Generated by Django 5.2.17 on 2026-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_sacar_prefijo_cortante_del_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_shipping_seller_paid',
            field=models.BooleanField(default=False, help_text='Si está activo, la publicación de Mercado Libre se marca con envío gratis y el costo del flete lo absorbe el vendedor — afecta la rentabilidad real, es una decisión de pricing, no solo técnica. Si el precio ya supera el piso que exige Mercado Libre para la categoría, el envío gratis se fuerza solo sin importar este flag. A diferencia de las dimensiones, este campo SÍ se puede actualizar en publicaciones ya existentes (no hace falta volver a crear el ítem).', verbose_name='Envío gratis (lo paga el vendedor)'),
        ),
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, help_text='Código de barras real del producto (EAN/UPC/ISBN, 8 a 14 dígitos), solo si lo tiene. Para piezas artesanales sin código de barras, dejar vacío — Mercado Libre valida el checksum y rechaza la publicación si se manda uno inventado. Se envía como atributo GTIN del ítem (mejora la calidad de la publicación si está disponible, pero no es obligatorio en esta categoría).', max_length=32, verbose_name='GTIN / código de barras'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Meses de garantía del vendedor que se informan en la publicación de Mercado Libre (sale_terms: WARRANTY_TYPE='Garantía del vendedor' + WARRANTY_TIME). Vacío = no se informa garantía en la publicación.", null=True, verbose_name='Garantía (meses)'),
        ),
    ]
