# Generated by Django 5.2.17 on 2026-10-09 16:59

from django.db import migrations
from django.db.models import Count, Q

# Mismo piso que mercadolibre/services.py::MIN_ML_PICTURES (no se importa directo
# porque las migraciones de datos no deben depender de código de la app que puede
# cambiar a futuro — se fija el valor vigente al momento de esta migración).
MIN_ML_PICTURES = 3


def apagar_ml_sin_fotos_suficientes(apps, schema_editor):
    """Apaga `is_available_ml` en los productos que hoy lo tienen prendido pero
    no llegan al piso de fotos que ahora exige tanto `sync_product()` para
    publicar como la validación nueva del admin (`ProductImageInlineFormSet`)
    para poder guardarse. Sin este backfill, cualquier producto en ese estado
    queda "trabado" (no se puede guardar su ficha completa) apenas alguien lo
    abra a editar, aunque no se haya tocado nada de Mercado Libre — se los pasa
    a `is_available_ml=False` para que el admin arranque consistente con la
    regla nueva; se reactivan a mano a medida que se les cargan las fotos que
    faltan.
    """
    Product = apps.get_model("products", "Product")
    productos_afectados = (
        Product.objects.filter(is_available_ml=True)
        .annotate(ml_photos=Count("images", filter=~Q(images__channel="web"), distinct=True))
        .filter(ml_photos__lt=MIN_ML_PICTURES)
    )
    productos_afectados.update(is_available_ml=False)


def revertir(apps, schema_editor):
    # No reversible de forma segura: no hay forma de distinguir, entre los
    # productos que quedan en is_available_ml=False, cuáles lo tenían así de
    # antes y cuáles los apagó esta migración — no-op a propósito.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_ml_gtin_warranty_free_shipping'),
    ]

    operations = [
        migrations.RunPython(apagar_ml_sin_fotos_suficientes, revertir),
    ]
