# Generated by Django 5.2.17 on 2026-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_actualizar_help_text_color_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_dishwasher_safe',
            field=models.BooleanField(blank=True, default=None, help_text="Si el producto es apto para lavavajillas. Se manda como atributo IS_DISHWASHER_SAFE de la publicación de Mercado Libre (Sí/No), solo si la categoría cargada lo admite. Dejalo en blanco ('Desconocido', valor vacío) si no corresponde informarlo — a diferencia de un booleano normal, acá 'vacío' no equivale a 'No': simplemente no se manda el atributo.", null=True, verbose_name='Apto para lavavajillas'),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(blank=True, help_text="Forma del producto (ej: Animal, Estrella, Número, Calabaza...) — se manda como atributo COOKIE_CUTTER_SHAPE de la publicación de Mercado Libre, solo si la categoría cargada lo admite (hoy MLA375405 'Cortantes' sí lo tiene — aparece en Mercado Libre como 'Características secundarias', suma a la calidad de la publicación). Texto libre: no hace falta que coincida con las opciones sugeridas de ML. Vacío = no se informa.", max_length=50, verbose_name='Forma'),
        ),
    ]
