# Generated by Django 5.2.17 on 2026-10-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_eliminar_canal_ambos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='ml_order',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='channel',
            field=models.CharField(choices=[('web', 'Página web'), ('ml', 'Mercado Libre')], default='web', help_text='A dónde se muestra esta foto. Cada foto pertenece a un solo canal — si la necesitás en los dos, cargala dos veces (una en cada apartado de Imágenes del admin).', max_length=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de la foto dentro de su canal (web o Mercado Libre).'),
        ),
    ]
