# Generated by Django 5.2.17 on 2026-10-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Solo esquema (CostTemplate + ProductVariant), sin la migración de
    datos — separada a propósito en 0035, igual criterio que
    `cart/migrations/0003_cart_por_marca.py` + `0004_cart_por_marca_schema.py`:
    Postgres no permite revertir un DROP TABLE en la misma transacción que
    un RunPython que borró filas de esa tabla ("pending trigger events").
    Con el RunPython en su propia migración, 0035 se puede revertir sola
    (borra las filas) y 0034 también (dropea las tablas ya vacías), sin
    pisarse entre sí.
    """

    dependencies = [
        ('products', '0033_eliminar_ml_order_y_both'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del presupuesto/perfil de costo, tal como se carga en presupuestos3d (ej: "Cortante 4cm", "Shaker grande"). Libre, sin límite de cantidad — a diferencia del viejo cutter_size, no está atado a un enum fijo de 5 valores.', max_length=100, unique=True)),
                ('external_ref', models.CharField(blank=True, help_text='Referencia estable del Producto de costeo en presupuestos3d que originó este template (la que viaja en el payload del sync). Se usa para hacer upsert por ID en vez de por nombre, así renombrar el presupuesto en presupuestos3d no rompe el link. Vacío en los templates migrados desde cutter_size (todavía no vienen de un sync real).', max_length=64, null=True, unique=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta a aplicar a todos los ProductVariant que referencien este template. Vacío = todavía no se sincronizó ningún precio desde presupuestos3d para este template (las variantes conservan su propio precio actual, sin tocarlo).', max_digits=10, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('legacy_cutter_size', models.CharField(blank=True, help_text='Valor de Product.cutter_size que originó este template en la migración inicial (0034) — solo trazabilidad histórica, no se usa en ningún cálculo nuevo.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de costo',
                'verbose_name_plural': 'Plantillas de costo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Tamaño')),
                ('sku', models.CharField(blank=True, max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gtin', models.CharField(blank=True, max_length=32, verbose_name='GTIN / código de barras')),
                ('is_available', models.BooleanField(default=True)),
                ('ml_variation_id', models.CharField(blank=True, help_text='ID de la variación en Mercado Libre, para cuando el ítem tenga variaciones reales publicadas (no usado todavía, Fase 1 publica igual que siempre a nivel Product).', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_template', models.ForeignKey(blank=True, help_text='Presupuesto de presupuestos3d del que toma precio/medidas esta variante. Vacío = variante con precio propio, no ligada a ningún presupuesto compartido (ej: producto a medida).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.costtemplate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de producto',
                'ordering': ['product', 'color', 'size'],
                'constraints': [models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_variant_per_product_color_size')],
            },
        ),
    ]
